In [1]:
import numpy as np

In [2]:
np.linspace(0,15,3001)

array([0.0000e+00, 5.0000e-03, 1.0000e-02, ..., 1.4990e+01, 1.4995e+01,
       1.5000e+01], shape=(3001,))

In [3]:
np.arange(1,5)

array([1, 2, 3, 4])

In [4]:
np.random.rand(15)

array([0.00677393, 0.60158278, 0.53668316, 0.15213291, 0.84171189,
       0.50413746, 0.95321514, 0.12823486, 0.82293803, 0.44081354,
       0.23600305, 0.16787799, 0.3553339 , 0.87338897, 0.97748134])

In [5]:
np.random.rand(15)*30

array([10.87052893, 25.2569791 , 12.98402352,  8.68969613,  1.29440017,
       20.75675997,  6.63432338, 11.09653863,  7.41158201, 20.598475  ,
       21.2439335 , 17.76273178, 25.0272595 , 12.87709194,  3.28218166])

In [6]:
srate = 1000 # Hz
time  = np.arange(0,3,1/srate)
time

array([0.000e+00, 1.000e-03, 2.000e-03, ..., 2.997e+00, 2.998e+00,
       2.999e+00], shape=(3000,))